version: '3.8'

services:
  backend:
    build: .
    image: task-management-system-java
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tasksystemDB
      - DB_USER=postgres
      - DB_PASSWORD=Kaiko1994Ulia
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tasksystemDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Kaiko1994Ulia
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kaiko1994Ulia
      - POSTGRES_DB=tasksystemDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: